Peering refactor
lunfardo314/proxima pull request #29
Opened 2024-11-03 19:03 UTC by HM4704

This peering refactor removes the creating and deleting of a stream for every send/receive. 
The streams are only created when a new peer is connected. 
This should avoid the problem of peer losses.

2024-11-04 07:25 UTC, lunfardo314 requested changes
needs review in an interactive session

2024-11-04 07:25 UTC, lunfardo314 commented on peering/misc.go
> +var writeMutex sync.Mutex
global mutex? Does not seem right

2024-11-04 07:25 UTC, lunfardo314 commented on peering/types.go
> +		CooloffListTTL int
comments would be nice

2024-11-10 17:38 UTC, HM4704 commented on peering/misc.go
> +var writeMutex sync.Mutex
Removed mutex.

2024-11-12 15:40 UTC, HM4704 commented on peering/types.go
> +		CooloffListTTL int
added comments

2024-11-19 15:26 UTC, merged