Api docu
lunfardo314/proxima pull request #37
Opened 2024-12-09 18:26 UTC by HM4704

This PR adds:
- docu for the API 
- tx api unit tests

2024-12-09 19:37 UTC, lunfardo314 requested changes
minor change requested

2024-12-09 19:37 UTC, lunfardo314 commented on api/server/txapi.go
> +	if metadata != nil {
not necessary, `JSONAble()` check if receiver is nil

2024-12-10 17:00 UTC, HM4704 commented on api/server/txapi.go
> +	if metadata != nil {
Fixed.

2024-12-11 07:53 UTC, lunfardo314 approved these changes

2024-12-11 07:53 UTC, merged